### PR TITLE
Abbey computer controller branch

### PR DESCRIPTION
**Pull request by brownabs**
# Description
I have created the computer controller with full crud and the testing class, and all tests passed

## Type of change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made
1. `git fetch --all`
1. `git checkout abbeyComputerControllerBranch`
1. dotnet run
1. verify...

# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

LINK FOR TICKET
https://github.com/nss-day-cohort-30/bangazon-api-whimsical-whooping-cranes/issues/9

### CODE REVIEW

**Review by katfree — COMMENTED** [review]
The purpose in test currently says "Controller for Computer" instead of "Test"

**Review by katfree — APPROVED** [review]
APPROVED.

**Review by MoSilvera — COMMENTED** [review]
Missing the "delete non existent"  from list of methods in  test file

**Review by MoSilvera — APPROVED** [review]
All tests passing, all documentation appears to be present. Good job! 👍

**Pull request merged**
